Repository TEAM-FLASH/Toucheese-FE, pull requests merged in 2024-12, with the labels that each got.

#16 Version 0.0 : 7차 배포 테스트
  .github/workflows/deploy.yml
  deploy.sh
Labels: Deploy

#17 Version 0.0 : 8차 배포 테스트
  .github/workflows/deploy.yml
Labels: Deploy

#18 Version 0.0 : 9차 배포 테스트
  .github/workflows/deploy.yml
  tsconfig.app.tsbuildinfo
Labels: Deploy

#20 Version 0.0: 10차 배포 테스트
  index.html
Labels: Deploy

#19 버튼 공통컴포넌트 UI를 구현하고 test 환경을 구축한다.
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/pages/Home/Home.tsx
  src/tests/Home.test.tsx
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
  vitest.setup.ts
Labels: UI, Test

#22 Version 0.0: 11차 배포 자동화 테스트
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/pages/Home/Home.tsx
  src/tests/Home.test.tsx
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
  vitest.setup.ts
Labels: Deploy

#23 공통컴포넌트 버튼 기능을 구현하고 test 환경을 구축한다
  src/components/Button/Button.test.tsx
Labels: Bug

#24 Version 0.0: 11차 배포 테스트
  src/components/Button/Button.test.tsx
Labels: Deploy

#25 Version 0.0: 11차 배포 테스트
  .github/workflows/deploy.yml
Labels: Deploy

#26 Version 0.0: 12차 배포 테스트
  .github/workflows/deploy.yml
Labels: Deploy

#27 Version 0.0: 12차 배포 테스트
  .github/workflows/deploy.yml
Labels: Deploy

#28 [S2] ThemeNavigator 컴포넌트 구현 및 테스트 코드 작성 완료
  src/components/Navigator/ThemeNavigator.test.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/PriceRangeInput/PriceRangeInput.tsx
  src/pages/Home/Home.tsx
Labels: UI, Test

#30 [S2] 양방향 인풋 레인지 컴포넌트 구현 완료
  .env
  src/components/FilterPriceSlide/FilterPriceSlide.test.tsx
  src/components/FilterPriceSlide/FilterPriceSlide.tsx
  src/components/FilterPriceSlide/PriceRangeInput.tsx
  src/pages/Home/Home.tsx
Labels: Feat, UI, Test

#32 [S2] full size 모달 구현 완료
  public/img/icon-close-btn.svg
  src/components/Modal/Modal.tsx
  src/hooks/useModal.ts
  src/store/useModalStore.ts
Labels: Feat

#33 [S2] 메인화면 스튜디오 아이템 컴포넌트 작업 중
  .github/workflows/deploy.yml
  .gitignore
  public/img/icon-bookmark-active.svg
  public/img/icon-bookmark-inactive.svg
  public/img/icon-location.svg
  public/img/icon-price.svg
  public/img/icon-rating.svg
  public/img/icon-time.svg
  src/App.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Studio/StudioList.tsx
  src/hooks/useGetStudios.ts
  src/hooks/useHook.ts
  src/pages/Home/Home.tsx
  src/types/types.ts
  src/utils/decodeSearchParams.ts
  src/utils/utils.ts
  tsconfig.app.json
  vite.config.ts
Labels: Feat, UI

#37 [S2] 지역, 날짜 설정 모달 페이지 구현 (기능 미완)
  public/img/icon-calendar.svg
  src/pages/Home/Home.tsx
  src/pages/Home/LocalDateSelectionModal.tsx
Labels: UI

#36 [S2] 메인 페이지 구현 작업 중
  src/components/Navigator/ThemeNavigator.tsx
  src/pages/Home/Home.tsx
Labels: UI

#39 공통 필터버튼 UI 기능을 구현한다
  public/img/icon-changing-room.svg
  public/img/icon-close.svg
  public/img/icon-makeup.svg
  public/img/icon-original-file.svg
  public/img/icon-parking.svg
  public/img/icon-photo-edit.svg
  public/img/icon-powder.svg
  public/img/icon-suit.svg
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
Labels: UI, Test

#43 [S2] pull requests 충돌로 인한 버그 수정
  public/img/icon-search.svg
  src/components/BookingSearchContainer/BookingSearchContainer.test.tsx
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/pages/Home/Home.tsx
Labels: Feat, UI, Test

#44 [S2] 공통 바텀 시트 기능 구현 (추후 기능 보강)
  src/components/BottomSheet/BottomSheet.tsx
  src/store/useBottomSheetStateStroe.ts
Labels: Feat, UI

#46 [S2] 메인화면 스튜디오 아이템 컴포넌트를 구현한다.
  package.json
  pnpm-lock.yaml
  src/components/Studio/StudioItem.tsx
  src/components/Studio/StudioList.tsx
  src/hooks/useGetStudios.ts
  src/pages/Home/Home.tsx
  src/types/types.ts
  src/utils/decodeSearchParams.ts
Labels: Feat, UI

#47 [S2] 캘린더 구현 완료
  public/img/icon-arrow-gray.svg
  src/components/Calendar/Calendar.tsx
Labels: Feat, UI

#49 [S2] 검색 페이지 구현 작업 중
  package.json
  pnpm-lock.yaml
  public/img/icon-arrowback.svg
  public/img/icon-search2.svg
  public/img/icon-xcircle.svg
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/ImageSwiper/ImageSwiper.tsx
  src/pages/search/Search.tsx
  src/pages/search/SearchResult.tsx
  src/pages/search/components/RecentSearches.test.tsx
  src/pages/search/components/RecentSearches.tsx
  src/pages/search/components/SearchBar.test.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/components/StudioList.tsx
  src/pages/search/components/TrendingStudios.tsx
  src/routes.tsx
Labels: Feat, UI, Test

#48 [S2] 메인에서 사용될 필터링 버튼 기능을 구현한다
  public/img/icon-reset.svg
  src/components/Button/Button.tsx
  src/components/Filter/Filter.tsx
  src/pages/Home/Home.tsx
Labels: Feat, UI

#50 [S2] 모달에 변경된 시안 적용 및 버튼 컴포넌트 적용
  public/img/icon-arrow-gray800.svg
  public/img/icon-close-btn.svg
  src/components/Modal/Modal.tsx
  src/pages/Home/LocalDateSelectionModal.tsx
Labels: UI

#51 [S2] 필터링 시 매장 서비스 제공 여부를 선택하는 컴포넌트 구현
  public/img/icon-room.svg
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/pages/Home/Home.tsx
Labels: Feat, UI, Refactor

#54 공통 버튼 컴포넌트 UI를 수정한다.
  src/components/Button/Button.tsx
  src/pages/Home/Home.tsx
Labels: Bug, UI, Hotfix

#55 [S2] 변경된 스타일 가이드 반영
  src/components/Modal/Modal.tsx
  src/components/Studio/StudioItem.tsx
  src/styles/Common.tsx
  src/styles/Variables.tsx
Labels: UI

#56 [S2] 스튜디오 아이템 이미지 슬라이드 추가
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/ImageSwiper/ImageSwiper.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Studio/StudioList.tsx
  src/pages/Home/Home.tsx
  src/types/types.ts
Labels: Feat, UI

#60 바텀시트 내 셀렉트 정렬 버튼 기능을 구현한다 ( 진행중 )
  public/img/icon-changing-room.svg
  public/img/icon-check.svg
  public/img/icon-room.svg
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterTextSelector.tsx
  src/pages/Home/Home.tsx
Labels: Feat, UI

#61 [S2] 필터링 기능 QA
  src/components/FilterPriceSlide/FilterPriceSlide.tsx
  src/components/Navigator/ThemeNavigator.tsx
Labels: Feat, UI

#57 Hotfix: 바텀 시트 max-height값 수정
  src/components/BottomSheet/BottomSheet.tsx
Labels: Hotfix

#62 [S2] 바텀시트 내 셀렉트 정렬 버튼 기능을 구현한다
  src/components/Filter/FilterTextSelector.tsx
  src/pages/Home/Home.tsx
Labels: Hotfix

#64 [S2] 메인 페이지 구현 중
  src/pages/Home/Home.tsx
  src/utils/decodeSearchParams.ts
Labels: Feat, UI

#65 [S2] 시간 선택 컴포넌트 구현 완료, 날짜 및 시간 선택 바텀 시트 추가
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/store/useSelectDate.ts
  src/store/useSelectTime.ts
  src/styles/Common.tsx
Labels: Feat, UI

#67 [S2] 타입 에러를 수정한다
  src/components/Filter/FilterTextSelector.tsx
Labels: Hotfix

#66 [S2] 검색 페이지 rem단위 변경, 쿼리 파라미터 변경
  src/pages/search/Search.tsx
  src/pages/search/SearchResult.tsx
  src/pages/search/components/RecentSearches.test.tsx
  src/pages/search/components/RecentSearches.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/components/StudioList.tsx
  src/pages/search/components/TrendingStudios.tsx
Labels: Feat

#70 [S2] 선택된 날짜 및 시간 값을 바텀시트 -> 모달 -> home으로 전달 기능 구현
  src/components/Calendar/Calendar.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/store/useSelectTime.ts
Labels: Feat, UI

#71 [S2] 메인페이지 UI 구현 및 API 연동 작업 완료
  src/components/Navigator/ThemeNavigator.tsx
  src/components/Studio/StudioList.tsx
  src/pages/Home/Home.tsx
Labels: Feat, UI

#73 [S2] 검색 페이지 버그 수정 및 API 연동 완료
  src/components/Message/EmptyMessage.tsx
  src/components/Studio/StudioList.tsx
  src/pages/search/Search.tsx
  src/pages/search/SearchResult.tsx
  src/pages/search/components/RecentSearches.test.tsx
  src/pages/search/components/RecentSearches.tsx
  src/pages/search/components/SearchBar.test.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/components/TrendingStudios.tsx
  src/routes.tsx
Labels: Bug, Feat, UI

#78 [S2] 메인 및 하위 컴포넌트의 테스트 코드를 작성한다.
  package.json
  pnpm-lock.yaml
  src/components/Studio/StudioItem.tsx
  src/components/Studio/StudioList.tsx
  src/tests/Home.test.tsx
  src/tests/StudioItem.test.tsx
  src/tests/StudioList.test.tsx
  src/tests/useGetStudios.test.tsx
  src/types/types.ts
  vite.config.ts
Labels: Refactor, Test

#79 [S2] QA : type 오류 수정
  src/components/ServiceAvailability/ServiceAvailability.tsx
  tsconfig.app.tsbuildinfo
Labels: Bug, Refactor

#83 Refactor : type 오류 수정 버튼 사용방법 변경으로 인한 수정
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
Labels: Bug, Feat, Refactor, Hotfix

#85 [S2] favicon을 추가한다.
  index.html
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/favicon-96x96.png
Labels: Feat

#87 Version 0.0.1: Story2 작업물 배포
  index.html
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/favicon-96x96.png
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Filter/FilterTextSelector.tsx
  src/components/FilterPriceSlide/FilterPriceSlide.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/store/useBottomSheetStateStore.ts
  src/tests/Home.test.tsx
Labels: Deploy

#88 [S2] SEO 강화를 위한 메타 태그 수정 및 robots.txt 작성
  index.html
  public/robots.txt
Labels: Docs, Chore

#91 Version 0.0.1: Story2 작업물 배포
  index.html
  public/robots.txt
Labels: Deploy

#94 [S3] 캘린더 테스트 코드 작성중
  package.json
  pnpm-lock.yaml
  src/components/Calendar/Calendar.test.tsx
  src/components/Calendar/Calendar.tsx
Labels: Test

#100 [S3] 검색 페이지 내 지역 선택 기능을 구현한다
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationSelectionModal.tsx
Labels: Feat, UI

#104 [S3] 정렬 필터링 기능을 수정한다
  src/components/Filter/FilterTextSelector.tsx
Labels: Hotfix

#108 [S3] 스튜디오 아이템의 img 태그에 alt 속성 추가
  src/components/Studio/StudioItem.tsx
Labels: Hotfix

#107 [S3] 복사 버튼 컴포넌트 구현
  src/components/CopyButton/CopyButton.tsx
Labels: Feat, UI

#112 [S3] 뒤로가기 버튼 공통 컴포넌트로 기능 수정
  src/components/BackButton/BackButton.tsx
  src/pages/search/Search.tsx
  src/pages/search/SearchResult.tsx
Labels: Feat

#113 [S3] 1차 리뷰 레이아웃 구현 및 studioReview 병합
  index.html
  public/img/icon-star-yellow.svg
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/ReviewImageList.tsx
Labels: Docs, Feat, UI, Refactor

#117 [S3] 캘린더, 지역 및 날짜 선택 모달 테스트 코드 작성
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  tests/Calendar.test.tsx
  tests/LocalDateSelectionModal.test.tsx
Labels: Test

#119 [S3] 상단 탭 구현 완료
  src/components/Navigator/StudioNavigator.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/routes.tsx
Labels: Feat, UI

#122 [S3] 메인 필터링 버튼 활성화 기능을 구현한다
  src/components/Filter/Filter.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottmSheet.tsx
Labels: Feat, Hotfix

#121 [S3] 이미지 슬라이드 기능 추가 구현
  src/components/ImageSwiper/ImageSwiper.tsx
Labels: Feat

#125 [S3] 바텀시트 드래그 기능 추가
  src/components/BottomSheet/BottomSheet.tsx
Labels: Feat

#126 [S3] reset 버튼 기능을 구현한다
  src/components/Filter/Filter.tsx
  src/pages/Home/Home.tsx
Labels: Hotfix

#129 [S3] 스튜디오 지도 기능 구현
  package.json
  pnpm-lock.yaml
  public/img/icon-content_copy.svg
  public/img/icon-map.svg
  src/components/CopyButton/CopyButton.tsx
  src/components/Kakao/KakaoMap.tsx
  tsconfig.json
Labels: Feat

#128 [S3] 버튼 공통 컴포넌트의 스타일을 수정한다
  src/components/Button/Button.tsx
  src/pages/Home/Home.tsx
Labels: UI, Hotfix

#131 [S3] Masonry list 구현
  package.json
  pnpm-lock.yaml
  src/components/Masonry/Masonry.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
Labels: Feat, UI

#132 [S3] 스튜디오 메뉴 목록 구현하다.
  public/img/icon-chevronright.svg
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/types/types.ts
Labels: Feat, UI

#134 Feat: 헤더 컴포넌트 구현
  src/components/Header/Header.tsx
Labels: Feat

#137 [S3] 지도 마커 이미지 변경
  public/img/icon-map-pin.svg
  src/components/Kakao/KakaoMap.tsx
Labels: UI

#139 [S3] 딤 모달 작업 중
  public/img/icon-close-gray500.svg
  public/img/icon-close-white.svg
  src/components/Bookmark/Bookmark.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/ImageSwiper/ImageSwiper.tsx
  src/components/Modal/Modal.tsx
  src/components/Studio/StudioItem.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Studio/StudioDimTest.tsx
  src/pages/Studio/components/DimmedModal.tsx
  src/routes.tsx
  src/types/types.ts
Labels: Feat, UI, Refactor

#140 [S3] 리뷰 관련 기능 고도화 및 ui, 리액트 쿼리를 통한 패칭 기능 구현
  index.html
  public/img/icon-arrow-down.svg
  public/img/icon-star-yellow.svg
  public/img/sample-1.png
  public/img/sample-2.png
  src/components/ImageSwiper/ImageSwiper.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/ReviewContent.tsx
  src/pages/Studio/StudioReview/components/ReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StarRating.tsx
  src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/styles/Common.tsx
  src/utils/formatTimeAgo.ts
Labels: Feat, UI

#142 [S3] 딤 모달 작업 중
  src/components/ImageSwiper/ImageSwiper.tsx
  src/components/Modal/Modal.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/pages/Studio/StudioDimTest.tsx
  src/pages/Studio/components/DimmedModal.tsx
  src/routes.tsx
Labels: UI

#144 [S3] 포트폴리오 페이지 진행중
  src/hooks/useGetStudios.ts
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/types/types.ts
  tests/StudioList.test.tsx
  tests/useGetStudios.test.tsx
Labels: Feat, UI

#146 [S3] 바텀시트 이벤트 핸들러 수정
  src/components/BottomSheet/BottomSheet.tsx
Labels: Hotfix

#149 [S3] 한개용 이미지 슬라이드 너비 조정
  src/components/ImageSwiper/ImageSwiper.tsx
Labels: UI

#151 [S3] 리뷰 고도화 작업 3차 완료
  public/img/icon-arrow-16.svg
  src/components/ImageSwiper/ImageSwiper.tsx
  src/hooks/useStudioReviews.ts
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/ReviewContent.tsx
  src/pages/Studio/StudioReview/components/StarRating.tsx
  src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  tests/ThemeNavigator.test.tsx
Labels: Bug, UI, Refactor, Hotfix, Test

#155 [S3] 메뉴 상세페이지 구현
  public/img/icon-camera-roll.svg
  public/img/icon-check-white.svg
  public/img/icon-crop.svg
  public/img/icon-folder.svg
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/types/types.ts
Labels: Feat, UI

#157 [S3] 공유하기 내부 링크복사 기능 구현
  public/img/icon-copy-link.svg
  src/components/CopyButton/CopyLocation.tsx
  src/components/Kakao/KakaoMap.tsx
  src/components/Share/Share.tsx
  src/hooks/useClipBoard.ts
Labels: Feat, UI

#159 [S3] 스튜디오 상세정보 페이지 포트폴리오 미리보기 기능을 구현한다
  src/hooks/useGetStudioDetail.ts
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/styles/Common.tsx
Labels: Feat, UI

#161 [S3] 메뉴 상세보기 리뷰 컴포넌트 구현
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/types/types.ts
Labels: Feat, UI, Hotfix

#163 [S3] 리뷰 기능 고도화 , 성능 최적화를 위한 코드스플리팅, SEO를 위한 페이지내 헬멧 추가
  src/App.tsx
  src/components/Error/ErrorBoundary.tsx
  src/components/ImageSwiper/ImageSwiper.tsx
  src/pages/Home/Home.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/ReviewContent.tsx
  src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/routes.tsx
Labels: Bug, Feat, Chore, Refactor, Hotfix

#165 [S3] 스튜디오 상세 홈 포트폴리오 미리보기의 더보기 기능을 구현한다
  public/img/icon-morePreview.svg
  src/components/Button/Button.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Feat, UI

#167 [S3] 공유하기 클립보드 기능 수정
  src/components/CopyButton/CopyLocation.tsx
  src/components/Kakao/KaKaoShare.tsx
  src/components/Share/Share.tsx
  src/components/Share/ShareButton.tsx
  src/components/Share/ShareOptions.tsx
  src/hooks/useClipBoard.ts
Labels: Feat, UI

#168 [S3] 북마크, 상단 탭 테스트 코드 작성 및 버그 수정
  public/img/icon-check-cheese800.svg
  public/img/icon-clock.svg
  public/img/icon-location.svg
  public/img/icon-map.svg
  public/img/icon-price.svg
  public/img/icon-time.svg
  src/components/Filter/FilterTextSelector.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/Studio/StudioItem.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
  tests/Bookmark.test.tsx
  tests/StudioNavigtor.test.tsx
  tests/ThemeNavigator.test.tsx
Labels: Hotfix, Test

#170 [S3] 이미지 슬라이드 스타일 수정
  src/components/ImageSwiper/ImageSwiper.tsx
Labels: UI

#171 [S3] 충돌 해결
  public/img/icon-none.svg
  src/components/ImageSwiper/ImageSwiper.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/components/ReviewContent.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
Labels: Bug

#178 [S3] 딤 모달 테스트 코드 작성
  tests/Dimmedmodal.test.tsx
Labels: Test

#181 Hotfix: 배포 테스트
  tests/Dimmedmodal.test.tsx
Labels: Deploy

#182 [S3] 스튜디오 상세정보 기능을 구현한다
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/types/types.ts
Labels: Feat, UI

#187 [S4] StudioItem, StudioDetail 타입 수정
  src/hooks/useGetStudioDetail.ts
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/types/types.ts
Labels: Hotfix

#188 [S4] 홈화면에서 로그인/마이페이지 라우팅 추가
  public/img/icon-search.svg
  public/img/icon-user-black.svg
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/pages/User/Login.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/SignUp.tsx
  src/routes.tsx
Labels: Feat, UI

#190 [S4] 스튜디오 상세정보 페이지 기능 구현 완료
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/types/types.ts
Labels: Feat, UI

#192 [S4] 딤 모달 내 스와이퍼 기능 작업중
  src/components/Modal/Modal.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Swiper/DimSwiper.tsx
  src/components/Swiper/ImageSwiper.tsx
  src/hooks/useModal.ts
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/Studio/components/DimmedModal.tsx
  src/store/useDimSwiper.ts
  src/types/types.ts
Labels: Feat

#193 [S4] 스튜디오 상세정보 페이지의 오류를 수정한다
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Hotfix

#194 [S4] 개인정보처리방침 모달 구현 완료
  src/pages/Reservation/components/PolicyModal.tsx
  src/styles/Common.tsx
Labels: UI

#195 [S4] 버튼 공통 컴포넌트의 스타일을 추가한다
  src/components/Button/Button.tsx
  src/components/Filter/Filter.tsx
  src/pages/Home/Home.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Hotfix
