Repository TEAM-FLASH/Toucheese-FE, pull requests merged in 2025-03, with the labels that each got.

#467 [WEB1] 스튜디오 포트폴리오 미리보기 대체 이미지 로직을 수정한다.
  public/img/img-replace-01.svg
  public/img/img-replace-02.svg
  public/img/img-replace-03.svg
  public/img/img-replace-04.svg
  public/img/img-replace-05.svg
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: UI, QA

#472 [QA2] 스튜디오 메뉴상세페이지 가로스크롤 이슈 해결
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: Hotfix, QA

#471 [WEB1] PC 버전 반응형 작업 중
  public/img/icon-nopic-mo.svg
  public/img/icon-nopic-pc.svg
  src/components/BookingSearchContainer/BookingButton.tsx
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/NoPic/NoPic.tsx
  src/components/PCHeader/PCHeader.tsx
  src/components/SearchButton/SearchButton.tsx
  src/components/Studio/StudioItem.tsx
  src/components/UserButton/UserButton.tsx
  src/pages/Home/Home.tsx
  src/styles/GlobalStyles.tsx
Labels: UI

#483 [WEB1] 북마크 등록/해제 로직 수정
  src/components/Bookmark/Bookmark.tsx
  src/hooks/useBookmark.ts
  src/routes.tsx
Labels: Refactor

#484 [WEB1] NoPic 컴포넌트 반응형 작업 완료
  src/components/NoPic/NoPic.tsx
Labels: UI

#482 [WEB1] 반응형 변수 정의 및 모달 반응형 구현
  src/components/Modal/Modal.tsx
  src/styles/BreakPoint.tsx
Labels: UI

#486 [WEB1] 홈화면 PC 반응형 작업중
  src/components/BookingSearchContainer/BookingButton.tsx
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Button/Button.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/PCHeader/PCHeader.tsx
  src/components/SearchButton/SearchButton.tsx
  src/components/Studio/StudioItem.tsx
  src/components/UserButton/UserButton.tsx
  src/hooks/useScrollToTop.ts
  src/pages/Home/Home.tsx
  src/styles/BreakPoint.tsx
Labels: UI

#469 [QA2] 이미지 스와이퍼 스타일 우선순위 수정 및 예역내역 'RESERVED' 타입 추가
  src/components/Swiper/ImageSwiper.tsx
  src/hooks/useGetReservationList.ts
Labels: Hotfix, QA

#487 [S5] 예약 취소 구현중
  src/components/Modal/Modal.tsx
  src/pages/Reservation/components/CancelModal.tsx
Labels: Feat, UI

#492 [WEB1] 모달 사용성 개선 완료
  src/components/Modal/Modal.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat, UI

#496 [WEB2] PC 헤더 공통컴포넌트로 변경
  src/components/Header/PCHeader.tsx
  src/components/PCHeader/PCHeader.tsx
  src/components/layout/Layout.tsx
  src/pages/Home/Home.tsx
Labels: Refactor

#494 [QA2] 모달 아이디 추가 및 스와이퍼 스타일 수정
  src/components/Swiper/ImageSwiper.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/LocationModal.tsx
Labels: Feat, QA

#499 [WEB1] 빌드 오류 해결
  src/pages/Reservation/ReservationDetail.tsx
  src/routes.tsx
Labels: Bug

#501 [WEB1] 반응형 가격 세션 구현 PC 작업 공유
  src/components/FilterPriceSlide/FilterPriceSlide.tsx
  src/components/FilterPriceSlide/FilterPriceSlidePC.tsx
  src/components/Input/Input.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/hooks/useStudioReviews.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/PCFilterWrapper.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
  src/pages/Studio/StudioReview/components/StarInput.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/store/useFilterStore.ts
Labels: Feat, Refactor, QA

#506 [WEB2] 배포용 환경변수 변경
  .github/workflows/deploy.yml
Labels: Chore

#508 [QA2] 스튜디오 메뉴페이지 에러 바운더리 적용
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: Refactor

#502 [QA2] header 컴포넌트 배경색 변화 로직 추가
  src/components/Header/Header.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
Labels: Feat, Refactor, QA

#509 [QA2] 예약상세페이지 API 연동
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Feat, QA

#497 [S5] 예약취소 완료 화면 id 추출 방식 변경
  src/pages/Reservation/ReservationCanceled.tsx
  src/routes.tsx
Labels: Refactor

#513 [WEB2] 메타 태그 보완 - 이미지, 트위터 정보 추가
  index.html
  public/og_image.png
Labels: Chore

#517 [QA2] 유저 정보 변경 기능 진행중
  src/components/Button/Button.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/User/AuthVerification.tsx
  src/pages/User/ChangePassword.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
  src/pages/User/SignUp.tsx
Labels: Bug, QA

#511 [WEB1] 검색 컴포넌트 PC버전 구현 및 스와이퍼 이미지 개수 조정
  package.json
  pnpm-lock.yaml
  src/components/Header/PCHeader.tsx
  src/components/Message/EmptyMessage.tsx
  src/components/Search/PCSearchBox.tsx
  src/components/Search/RecentSearches.tsx
  src/components/Search/SearchBar.tsx
  src/components/Search/TrendingStudios.tsx
  src/components/Swiper/ImageSwiper.tsx
  src/pages/search/Search.tsx
  src/pages/search/SearchResult.tsx
  src/pages/search/components/SearchBar.tsx
Labels: Feat, UI

#521 [WEB1] PC 버전 필터링 부분 기능 공유 <utils, chips, layout > 수정
  public/img/icon-close-small.svg
  public/img/img-pc_AuthPage.svg
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/pages/Home/components/PCFilterWrapper.tsx
  src/pages/User/Auth.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/utils/formatPrice.ts
Labels: Feat, Refactor

#522 [WEB2] PC버전 메인페이지 스튜디오 정렬 기능을 구현한다
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterSort.tsx
  src/pages/Home/Home.tsx
  src/store/useFilterStore.ts
  src/types/types.ts
Labels: Feat, UI, QA

#524 [WEB2] PC 버전 Studio 정렬 기능을 적용한다.
  src/components/Filter/FilterSort.tsx
  src/pages/Home/components/PCFilterWrapper.tsx
Labels: Feat, QA

#526 [WEB2] PC 버전 토스트 구현
  src/components/ReservationFooter/ReservationFooter.tsx
  src/components/Toast/Toast.tsx
  src/pages/Home/Home.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: UI, Hotfix

#528 Cont: PC버전 StudioNavigator 작업 중
  src/components/Navigator/StudioNavigator.tsx
Labels: UI

#531 [WEB2] 포트폴리오 상세 PC 반응형 구현
  src/components/Masonry/Masonry.tsx
  src/components/Modal/Modal.tsx
  src/components/Swiper/DimSwiper.tsx
  src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
Labels: Feat, UI

#536 [QA2] 날짜/시간 선택시, 지나간 시간 비활성화
  src/pages/Home/components/SelectTime.tsx
Labels: Feat

#541 [WEB1] PC 홈화면 수정
  public/img/icon-search-gray700.svg
  src/components/Filter/FilterSort.tsx
  src/components/Search/SearchBar.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PCFilterWrapper.tsx
  src/pages/search/Search.tsx
Labels: UI

#543 [WEB2] 스튜디오 상세정보 데이터를 Session Storage에 저장한다
  src/components/Studio/StudioInfo.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/User/ChangePassword.tsx
  src/store/useStudioDataStore.ts
Labels: Feat, QA

#542 [WEB1] PC 필터 영역 스크롤 수정
  src/pages/Home/Home.tsx
Labels: UI, QA

#544 [WEB2] PC 버전 스튜디오 상세 고정 영역 작업 중
  src/components/Header/Header.tsx
  src/components/Header/PCHeader.tsx
  src/components/Navigator/StudioNavigator.tsx
Labels: UI

#545 [WEB2] 스튜디오 상세 오른쪽 고정영역 작업 중
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioInfoDock.tsx
  src/components/Studio/StudioOptions.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: UI

#549 [WEB2] 빌드 에러 해결
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/ReservationList.tsx
  tests/RecentSearches.test.tsx
Labels: Bug

#539 [WEB2] 반응형 작업 진행 중, 유효성 검사 라이브러리 배포 후 변경
  package.json
  pnpm-lock.yaml
  src/pages/User/LoginWithEmailPage.tsx
  src/types/wj-password-validator.d.ts
Labels: Docs, Feat, Refactor

#550 [WEB2] 스튜디오 메인 페이지의 반응형 구조를 적용한다.
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: UI

#552 [WEB2] 스튜디오 상세 오른쪽 영역 작업 중
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioInfoDock.tsx
Labels: Bug

#547 [Hotfix] 주소 변경으로 인한 환경설정 변경
  index.html
  public/robots.txt
  public/sitemap.xml
Labels: Hotfix

#538 [WEB2] 1차 스튜디오 메뉴 페이지 PC버전 구현
  src/components/ReservationFooter/ReservationFooter.tsx
  src/components/Swiper/ImageSwiper.tsx
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
Labels: UI

#553 [WEB2] 스튜디오 상세 오른쪽 영역 작업 중
  public/img/icon-share.svg
  src/components/BookingSearchContainer/BookingButton.tsx
  src/components/Bookmark/Bookmark.tsx
  src/components/Header/Header.tsx
  src/components/Header/PCHeader.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/Share/ShareButton.tsx
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioInfoDock.tsx
  src/components/Studio/StudioOptions.tsx
  src/pages/Home/Home.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/styles/Common.tsx
  src/styles/GlobalStyles.tsx
Labels: UI

#557 [WEB1] PC 헤더 z-index 변경
  src/components/Header/PCHeader.tsx
  src/components/Studio/StudioInfoDock.tsx
Labels: Bug, UI

#556 [WEB2] 버튼 컴포넌트 변경 내역 반영
  src/components/Modal/Modal.tsx
  src/components/Swiper/DimSwiper.tsx
  src/pages/Reservation/components/CancelModal.tsx
Labels: Bug

#560 [WEB1] PC버전 NoResult 컴포넌트 구현 완료
  public/img/icon-noresult.svg
  src/components/BookingSearchContainer/BookingButton.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/NoResult/NoResult.tsx
  src/components/Studio/StudioList.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PCFilterWrapper.tsx
  src/pages/Reservation/ReservationList.tsx
  src/styles/Common.tsx
Labels: UI

#562 [Hotfix] 예약 내역 조회 Hook의 에러 수정
  src/hooks/useGetReservationList.ts
Labels: Bug

#554 [WEB2] 스튜디오 상세 오른쪽 고정 영역 적용 중
  src/components/Studio/StudioInfoDock.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/PolicyModal.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/PasswordConfirm.tsx
  src/routes.tsx
Labels: UI

#564 Version 0.5.0: WEB2 작업 내용 배포
  .github/workflows/deploy.yml
Labels: Deploy

#573 [WEB1] PC 헤더의 검색창 크기 변경
  src/components/Header/PCHeader.tsx
  src/components/Search/SearchBar.tsx
  src/pages/Home/Home.tsx
Labels: UI

#575 [WEB3] PC 버전 개인정보처리방침 모달의 UI 변경
  src/pages/Reservation/components/PolicyModal.tsx
Labels: UI
