Repository TEAM-FLASH/Toucheese-FE, pull requests merged in 2025-01, with the labels that each got.

#196 [S4] 스튜디오 예약 확인 화면 구현중
  package.json
  pnpm-lock.yaml
  public/img/icon-check-gray.svg
  public/img/icon-checkbox-done.svg
  public/img/icon-checkbox-empty.svg
  src/pages/Reservation/ReservationCheck.tsx
  src/routes.tsx
Labels: Feat, UI

#197 [S4] 딤 모달 내 스와이퍼 기능 구현 완료
  src/components/Modal/Modal.tsx
  src/components/Swiper/DimSwiper.tsx
  src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/components/DimmedModal.tsx
  src/store/useDimSwiper.ts
  src/types/types.ts
Labels: Feat, UI

#198 Version 0.1.0: Story 3 작업물 배포
  package.json
  pnpm-lock.yaml
  public/img/icon-check-gray.svg
  public/img/icon-checkbox-done.svg
  public/img/icon-checkbox-empty.svg
  public/img/icon-search.svg
  public/img/icon-user-black.svg
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Button/Button.tsx
  src/components/Filter/Filter.tsx
  src/components/Modal/Modal.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Swiper/DimSwiper.tsx
  src/components/Swiper/ImageSwiper.tsx
  src/hooks/useGetStudioDetail.ts
  src/hooks/useModal.ts
  src/pages/Home/Home.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/components/PolicyModal.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/Studio/components/DimmedModal.tsx
  src/pages/User/Login.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/SignUp.tsx
  src/routes.tsx
  src/store/useDimSwiper.ts
  src/styles/Common.tsx
  src/types/types.ts
Labels: Deploy

#199 Version 0.1.0: Story 3 작업물 배포
  src/types/types.ts
  tests/StudioItem.test.tsx
  tests/StudioList.test.tsx
  tests/useGetStudios.test.tsx
Labels: Deploy

#200 Version 0.1.1: Story 3 작업물 긴급 수정
  .github/workflows/deploy.yml
Labels: Deploy, Hotfix

#204 [S4] 이전 기록이 없을 시 기본 경로 이동
  src/components/BackButton/BackButton.tsx
Labels: Bug, Feat

#205 [S4] 메인페이지 필터링 영역의 백그라운드 컬러 오류를 수정한다
  src/pages/Home/Home.tsx
Labels: Hotfix

#206 [S4] 예약 과정 라우팅 설정
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/routes.tsx
Labels: Feat

#209 [S4] 포트폴리오 필터링 구현 완료
  .prettierrc.cjs
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/styles/Variables.tsx
Labels: Feat, Chore, Refactor

#210 [S4] 로그인 페이지 UI 및 라우팅 수정 작업
  index.html
  public/img/icon-emailSymbol.svg
  public/img/icon-googleSymbol.svg
  public/img/icon-kakaoSymbol.svg
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Input/Input.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/User/Auth.tsx
  src/pages/User/Login.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/components/LoginTypeButton.tsx
  src/routes.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat

#214 [S4] ReservationCheck 이중 호출 오류 개선
  src/routes.tsx
Labels: Hotfix

#215 [S4] 지도보기 버튼 추가 및 경로 수정
  src/components/Kakao/KakaoMap.tsx
Labels: Feat, UI, Hotfix

#219 [S4] 스튜디오 상세정보 페이지 최적화 기능을 완료한다
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Feat

#221 [S4] 예약 버튼 공통 컴포넌트로 분류한다.
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/store/useReservationStore.ts
Labels: Feat

#223 [S4] 메뉴 상세페이지의 이미지 스와이퍼 경로를 수정한다.
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: Hotfix

#225 [S4] 인풋 컴포넌트 고도화 작업 진행
  src/App.tsx
  src/components/Input/Input.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/ReviewContent.tsx
  src/pages/User/Auth.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/components/LoginTypeButton.tsx
Labels: Feat, UI, QA

#226 [S4] 예약 완료 페이지 구현
  public/img/icon-calendar-black.svg
  public/img/icon-complete-cheese500.svg
  public/img/icon-none.svg
  src/pages/Reservation/ReservationComplete.tsx
  src/styles/Common.tsx
Labels: Feat, UI

#228 [S4] 회원가입 페이지 UI를 구현한다
  src/components/Button/Button.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/User/SignUp.tsx
Labels: Feat, UI

#229 [S4] 이니시스 결제 기능 구현 및 인풋창 기능 추가
  index.html
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Feat

#233 [S4] 인풋 기능 수정
  src/components/Input/Input.tsx
  src/pages/User/Auth.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/SignUp.tsx
Labels: Feat

#237 [S4] 바텀시트 배경 layout shift 이슈 해결
  src/components/BottomSheet/BottomSheet.tsx
Labels: Bug, Hotfix

#240 [S4] 예약 페이지 구현중, 날짜 및 시간 선택 컴포넌트 고도화, 모달 고도화
  public/img/icon-calendar-black.svg
  public/img/icon-clock-black.svg
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/store/useSelectDate.ts
  src/store/useSelectTime.ts
  src/styles/Common.tsx
Labels: Feat, UI

#242 [S4] 예약 페이지 - ReservationFooter 추가
  src/pages/Reservation/ReservationSchedule.tsx
Labels: Feat

#243 [S4] 카카오페이 테스트 결제 구현중
  public/img/icon-kakaoPay.svg
  public/img/icon-naverPay.svg
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Feat

#245 [S4] 사용자 회원가입 간편 본인인증 기능을 구현한다.
  src/pages/User/SignUp.tsx
Labels: Feat

#248 [S4] 스튜디오 주소가 길면 UI가 깨지는 현상 수정
  src/components/Studio/StudioItem.tsx
Labels: QA

#250 [S4] 예약 완료 화면 스타일 수정
  src/pages/Reservation/ReservationComplete.tsx
Labels: UI

#252 [S4] 시간 선택 컴포넌트 고도화 작업중
  public/img/icon-info.svg
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/store/useSelectDate.ts
  tests/Calendar.test.tsx
  tests/SelectTime.test.tsx
Labels: Feat, UI, Test

#253 [S4] 메뉴 예약하기 전 로그인 유무 로직 구분
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/store/useReservationStore.ts
Labels: Bug, Feat

#254 [S4] 회원가입 페이지의 본인인증 기능을 팝업창으로 분류한다.
  src/pages/User/SignUp.tsx
Labels: Feat

#255 Version 0.2.0: Story 4 작업물 테스트 배포
  .github/workflows/deploy.yml
  .prettierrc.cjs
  index.html
  public/img/icon-calendar-black.svg
  public/img/icon-cancel.svg
  public/img/icon-clock-black.svg
  public/img/icon-complete-cheese500.svg
  public/img/icon-emailSymbol.svg
  public/img/icon-error.svg
  public/img/icon-eye-off.svg
  public/img/icon-eye.svg
  public/img/icon-googleSymbol.svg
  public/img/icon-info.svg
  public/img/icon-kakaoPay.svg
  public/img/icon-kakaoSymbol.svg
  public/img/icon-naverPay.svg
  public/img/icon-none.svg
  src/App.tsx
  src/components/BackButton/BackButton.tsx
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Input/Input.tsx
  src/components/Kakao/KakaoMap.tsx
  src/components/Modal/Modal.tsx
  src/components/ReservationFooter/ReservationFooter.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Toast/Toast.tsx
  src/hooks/useToast.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Reservation/components/Payment.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/components/ReviewContent.tsx
  src/pages/User/Auth.tsx
  src/pages/User/Login.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/SignUp.tsx
  src/pages/User/components/LoginTypeButton.tsx
  src/routes.tsx
  src/store/useReservationStore.ts
  src/store/useSelectDate.ts
  src/store/useSelectTime.ts
  src/store/useToastStore.ts
  src/styles/Common.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Variables.tsx
  tests/Calendar.test.tsx
  tests/SelectTime.test.tsx
Labels: Deploy

#256 [S4] 네이버페이 테스트 결제 구현
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Feat

#258 [S4] 바텀시트 모바일 스크롤 이슈 해결
  src/components/BottomSheet/BottomSheet.tsx
Labels: Hotfix, QA

#260 [S4] 스튜디오 필터링 : 선택된 날짜, 시간, 지역 전달
  src/pages/Home/components/LocalDateSelectionModal.tsx
Labels: Feat

#263 [S4] 카카오 로그인을 위한 함수 구현
  index.html
  package.json
  pnpm-lock.yaml
  src/pages/User/Auth.tsx
  src/pages/User/KakaoCallback.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/routes.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat

#265 [S4] 스튜디오 필터링(장소, 일시) 구현 완료 및 메인 반영
  public/img/icon-info-gray600.svg
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/store/useSelectDate.ts
Labels: Feat, UI

#268 [S4] 리뷰 모아보기 페이지에 딤 모달 스와이퍼 적용
  src/components/Swiper/DimSwiper.tsx
  src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
Labels: Feat, UI, QA

#269 [S4] 메뉴 예약 정보 SessionStorage 저장 위치 수정
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/store/useReservationStore.ts
Labels: Feat, Hotfix

#271 [S4] 로그인 , 이메일 구현 중 리뷰 사진 모아보기 구현 완료
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
  src/pages/User/Auth.tsx
  src/pages/User/KakaoCallback.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/routes.tsx
  src/types/types.ts
Labels: Feat

#270 [S4] 회원가입 페이지의 본인인증완료 후 입력 데이터 저장 기능을 구현한다
  .gitignore
  src/components/Input/Input.tsx
  src/pages/User/AuthVerification.tsx
  src/pages/User/SignUp.tsx
  src/routes.tsx
  src/store/useSignupStore.ts
  src/store/useUserStore.ts
Labels: Feat

#276 [S4] 예약확인 페이지 실제 데이터 값으로 변경
  public/img/icon-share.svg
  src/components/Share/ShareButton.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/components/Payment.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: Feat

#277 [S4] 헬멧 및 헤딩 태그 추가 - 포트폴리오, 예약하기
  index.html
  src/components/Calendar/Calendar.tsx
  src/components/Swiper/DimSwiper.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
Labels: Chore

#278 [S4] 메뉴 목록,상세페이지 SEO추가 및 Heading태그 수정
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
Labels: Feat, Refactor

#279 [S4] 구글 로그인 로직 추가
  .github/workflows/deploy.yml
  public/img/icon-bookmark-inactive.svg
  src/pages/User/Auth.tsx
  src/pages/User/GoogleCallback.tsx
  src/routes.tsx
Labels: Feat, QA

#280 [S4] User 전역 상태 추가 작업 중
  src/store/useUserStore.ts
  src/types/types.ts
Labels: Feat

#282 [S4] User 전역 상태 추가 작업 중
  src/pages/User/MyPage.tsx
Labels: Feat

#284 [S4] 검색 및 검색 결과페이지에 SEO 추가
  src/pages/search/Search.tsx
  src/pages/search/SearchResult.tsx
Labels: Feat

#285 [S4] User 정보 로컬 스토리지에 저장
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/pages/User/GoogleCallback.tsx
  src/pages/User/MyPage.tsx
  src/store/useUserStore.ts
  src/types/types.ts
  src/utils/getLocalStorageItem.ts
Labels: Feat, Refactor

#287 [S4] 로그인 기능 구현 중
  public/sitemap.xml
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
  src/pages/User/Auth.tsx
  src/pages/User/KakaoCallback.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/routes.tsx
Labels: Feat

#289 [S4] 결제하기 버튼 구현
  src/pages/Reservation/components/Payment.tsx
Labels: UI

#291 [S4] 이메일로 로그인 기능구현 완료
  public/sitemap.xml
  src/pages/User/Auth.tsx
  src/pages/User/LoginWithEmailPage.tsx
Labels: Feat

#294 [S4] 변경된 회원가입 페이지의 UI를 구현한다
  src/components/Button/Button.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/User/AuthVerification.tsx
  src/pages/User/SignUp.tsx
Labels: UI, Refactor

#295 [S4] 예약 완료 데이터 불러오기
  .github/workflows/deploy.yml
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/components/Swiper/DimSwiper.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Reservation/components/PolicyModal.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/store/useDimSwiperStore.ts
  src/store/useSelectDateStore.ts
  src/store/useSelectTimeStore.ts
  tests/Calendar.test.tsx
  tests/LocalDateSelectionModal.test.tsx
Labels: Feat

#296 [S4] 매뉴 상세페이지 QA를 진행한다.
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/store/useReservationStore.ts
Labels: Hotfix, QA

#299 [S4] 카카오페이 결제시 고유 주문번호 수정
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Hotfix

#301 [S4] 스튜디오 메인페이지 네비게이트와 본인인증 라우터 추가
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/User/AuthVerification.tsx
  src/routes.tsx
Labels: Refactor, Hotfix

#304 [S4] 메뉴 상세페이지 로그인 유무 로직 구분 추가
  src/pages/Home/Home.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: Feat

#302 [S4] User 전역 상태 초기화 방법 변경
  src/store/useUserStore.ts
  src/types/types.ts
Labels: Hotfix

#311 [S5] 예약 정보, 상세, 취소 완료 라우팅 추가
  src/pages/Reservation/ReservationCanceled.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/ReservationList.tsx
  src/routes.tsx
Labels: Chore

#314 [S5] 선택된 날짜 및 시간 전역 값을 세션 스토리지에 저장
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/store/useSelectDateStore.ts
  src/store/useSelectTimeStore.ts
Labels: UI, QA

#315 [S5] 마이페이지 라우팅 정보 추가 및 페이지 생성
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/ChangePassword.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/MyReviews.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
  src/routes.tsx
Labels: Feat

#316 [S4] 카카오 로그인 기능 구현 완료
  src/pages/User/Auth.tsx
  src/pages/User/KakaoCallback.tsx
Labels: Feat

#318 [S5] 선택된 날짜 및 시간 초기화, 선택되지 않은 경우 예외 처리
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/store/useSelectDateStore.ts
  src/store/useSelectTimeStore.ts
Labels: Bug, Feat

#319 [S5] 예약 완료/취소 UI 공통화
  src/pages/Reservation/ReservationCanceled.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/components/CompleteMessage.tsx
Labels: UI

#320 [S5] 예약 완료 후 날짜, 시간 초기화
  src/pages/Reservation/ReservationCanceled.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/components/CompleteMessage.tsx
Labels: Refactor

#321 [S5] 예약 정보 확인 기능 구현
  public/img/icon-noreservation.svg
  src/components/Navigator/ReservationNavigator.tsx
  src/hooks/useGetReservationList.ts
  src/pages/Reservation/ReservationList.tsx
Labels: Feat, UI

#322 [S4] 리뷰 작성 페이지 라우팅 및 컴포넌트 구현
  public/img/icon-star-filled.svg
  public/img/icon-star-notfilled.svg
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
  src/pages/Studio/StudioReview/components/ImageUploadPreview.tsx
  src/pages/Studio/StudioReview/components/StarInput.tsx
  src/pages/User/Auth.tsx
  src/routes.tsx
Labels: Feat, UI

#324 [S5] 본인인증 기능 오류를 해결하고 이메일 중복 확인 기능을 구현한다.
  src/pages/User/AuthVerification.tsx
  src/pages/User/SignUp.tsx
  src/store/useSignupStore.ts
Labels: Feat, Hotfix

#330 [S5] 인풋 요구사항 변경으로 인한 수정
  public/img/icon-valid.svg
  src/components/Input/Input.tsx
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
Labels: Feat

#332 [S5] 마이페이지 UI 구현 및 예약카드 공통 컴포넌트 분류
  public/img/icon-arrow-right-black.svg
  public/img/icon-calendar-yellow.svg
  public/img/icon-myreview.svg
  public/img/icon-rating-disabled.svg
  public/img/icon-rating.svg
  public/img/icon-studio-black.svg
  public/img/icon-studio-yellow.svg
  src/components/ReservationCard/RatingReview.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/components/ReservationCard/StatusChip.tsx
  src/pages/User/MyPage.tsx
  src/styles/Common.tsx
Labels: Feat, UI

#334 [S5] 예약 카드 적용 테스트
  src/components/ReservationCard/RatingReview.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/User/MyPage.tsx
Labels: Feat

#335 [S5] 결제 API 연동 및 예약 정보 전역상태로 저장
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/Payment.tsx
  src/store/useReservationStore.ts
Labels: Feat

#336 [S5] 예약 취소 모달 구현 및 input, textarea, default modal UI 작업
  public/img/icon-check-white-radius.svg
  src/components/Modal/Modal.tsx
  src/components/TextArea/TextArea.tsx
  src/pages/Reservation/components/CancelModal.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat, UI

#339 [S5] 예약화면 라디오 버튼 UI 수정 및 결제창 실제 값 변경
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Feat, UI

#341 [S5] 이메일 회원가입 기능을 구현한다.
  src/components/Input/Input.tsx
  src/pages/User/AuthVerification.tsx
  src/pages/User/SignUp.tsx
  src/pages/User/signupSuccess.tsx
  src/routes.tsx
  src/store/useSignupStore.ts
Labels: Feat, UI, Hotfix

#342 [S5] 예약 가능 일시 API 호출 및 반영
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/createCalendar.tsx
  src/hooks/useGetAvailableDate.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationSchedule.tsx
Labels: Bug, Feat, UI

#343 [S5] 리뷰 작성 및 상세보기 리뷰 성능 개선
  package.json
  pnpm-lock.yaml
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
Labels: Feat

#344 [S5] 예약 내역 조회 기능 추가
  src/components/Navigator/ReservationNavigator.tsx
  src/hooks/useGetReservationList.ts
  src/pages/Reservation/ReservationList.tsx
  src/types/types.ts
Labels: Feat

#347 [S5] 마이페이지 예약 카드 swiper 기능 추가
  src/components/ReservationCard/ReservationCard.tsx
  src/components/ReservationCard/StatusChip.tsx
  src/pages/User/MyPage.tsx
Labels: Feat, UI

#348 [S5] 유저 정보관리 페이지 UI구현 및 기능 구현을 완료한다
  src/pages/User/ChangeProfile.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
Labels: Feat
