Repository TEAM-FLASH/Toucheese-FE, pull requests merged in 2025-04, with the labels that each got.

#574 [WEB2] 스튜디오 상세 오른쪽 영역 - 데이터 불러오기 로직 수정
  src/components/Studio/StudioInfoDock.tsx
  src/pages/Studio/StudioDetailLayout.tsx
Labels: Bug

#576 [WEB2] PC버전에서 스튜디오 공유하기 UI를 바텀시트 -> 모달로 변경
  src/components/Share/ShareButton.tsx
  src/components/Share/ShareModal.tsx
  src/components/Share/ShareOptions.tsx
Labels: UI

#578 [WEB3] PC 버전 예약 완료 화면 구현
  src/pages/Reservation/components/CompleteMessage.tsx
Labels: UI

#579 [WEB1] 메인화면에서 Swiper로 인해 발생하는 에러 해결
  src/components/Studio/StudioItem.tsx
Labels: Bug

#581 [WEB1] PC버전 홈화면 필터 영역의 z-index 수정
  src/pages/Home/Home.tsx
Labels: UI

#583 [Docs] README.md 임시 레이아웃 작성
  README.md
Labels: Docs

#585 [WEB1] PC버전 StudioItem에서 발생하는 `key` 에러 해결
  src/components/Studio/StudioItem.tsx
  src/pages/Home/Home.tsx
Labels: Bug

#586 [Docs] README.md 작성 중
  README.md
Labels: Docs

#587 [WEB2] 모달 zindex 조정
  src/components/Modal/Modal.tsx
Labels: UI

#597 [WEB2] 리뷰 페이지 예외처리 및 반응형 작업
  src/components/Input/Input.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/User/LoginWithEmailPage.tsx
Labels: Feat

#604 [WEB3] 지역 필터링 UI 모달/바텀시트 조건부 렌더링 및 공통 컴포넌트 분리
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
  src/pages/Home/components/LocationModal.tsx
  src/pages/Home/components/LocationSelector.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Refactor, Hotfix

#606 [WEB3] 스튜디오 메인 페이지의 데이터 누락 문제 해결
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Hotfix

#608 [WEB3] 버튼 공통 컴포넌트의 색상 스타일을 추가한다
  src/components/Button/Button.tsx
Labels: UI, QA

#610 [WEB3] 텍스트 길이에 따른 더보기 버튼의 조건부 렌더링 처리를 한다.
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Hotfix

#601 Version 0.6.0: WEB3 작업물 배포
  README.md
  public/img/img-menu-nopic.png
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Header/PCHeader.tsx
  src/components/Input/Input.tsx
  src/components/Modal/Modal.tsx
  src/components/ReservationFooter/ReservationFooter.tsx
  src/components/Search/SearchBar.tsx
  src/components/Share/ShareButton.tsx
  src/components/Share/ShareModal.tsx
  src/components/Share/ShareOptions.tsx
  src/components/Studio/StudioInfoDock.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Studio/StudioOptions.tsx
  src/components/Swiper/DimSwiper.tsx
  src/components/Swiper/ImageSwiper.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
  src/pages/Home/components/LocationModal.tsx
  src/pages/Home/components/LocationSelector.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Reservation/components/CompleteMessage.tsx
  src/pages/Reservation/components/Payment.tsx
  src/pages/Reservation/components/PolicyModal.tsx
  src/pages/Reservation/components/ReservationInfo.tsx
  src/pages/Reservation/components/ScheduleInner.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/styles/Variables.tsx
Labels: Deploy

#614 [WEB3] 예약상세API HTTP 메서드 변경
  src/pages/Reservation/ReservationDetail.tsx
Labels: Hotfix

#617 [WEB2] 스튜디오 상세 오른쪽 고정 영역의 너비 및 내부 스타일 수정
  src/components/Header/PCHeader.tsx
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioInfoDock.tsx
Labels: UI

#612 [WEB3] 마이페이지 PC 반응형 적용
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/User/MyPage.tsx
Labels: Feat, UI

#616 [WEB3] 유저 정보 및 계정 정보 변경 기능을 구현한다.
  src/pages/User/ChangePassword.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
Labels: Feat, Hotfix

#621 [WEB3] 예약 취소 POST 구현
  src/components/Modal/Modal.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/CancelModal.tsx
Labels: Feat, UI

#619 [WEB3] 예약상세 PC화면 구현
  index.html
  src/components/Kakao/KakaoMap.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/LocationModal.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Feat, UI

#625 [WEB2] 스튜디오 상세 탭 공통 적용 - PC 반응형에서 모바일 전용 일괄 미노출
  src/components/Navigator/StudioNavigator.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
Labels: UI

#633 [S2] 홈화면 북마크 적용 완료
  src/components/Bookmark/Bookmark.tsx
  src/hooks/useBookmark.ts
  src/hooks/useGetStudios.ts
Labels: Feat, Refactor

#632 [WEB2] 리뷰 모달 반응형 구현 및 딤모달 스타일 개선
  src/components/Modal/Modal.tsx
  src/components/Swiper/DimSwiper.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
  src/pages/Home/components/LocationModal.tsx
  src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
Labels: UI

#636 [Docs] README.md 파일 수정
  README.md
Labels: Docs

#640 [WEB1] PC버전 홈화면 필터 - 스튜디오 목록 간격 수정
  src/components/Studio/StudioItem.tsx
  src/pages/Home/Home.tsx
Labels: UI

#642 [Docs] README.md 파일 수정 - 팀원 사진 교체
  README.md
Labels: Docs

#643 [Docs] README.md 파일 수정 - 스타일 수정
  README.md
Labels: Docs

#646 [WEB3] 유저 정보 AES암호화 로직 적용 및 로그인 로직 개선
  package.json
  pnpm-lock.yaml
  src/hooks/useLoginMutation.ts
  src/pages/User/AuthVerification.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/Profile.tsx
  src/store/useUserStore.ts
  src/utils/encryptUserData.ts
Labels: UI, Refactor

#645 [WEB3] "메뉴 상세 - 예약 스케줄 선택 - 예약 결제" PC 레이아웃 개선 및 통일
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Reservation/components/ScheduleInner.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
Labels: UI

#644 Version 0.7.0: WEB4 작업 내용 배포
  .github/workflows/deploy.yml
  README.md
  package.json
  pnpm-lock.yaml
  src/components/Bookmark/Bookmark.tsx
  src/components/Header/PCHeader.tsx
  src/components/Kakao/KakaoMap.tsx
  src/components/Modal/Modal.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/NoResult/NoResult.tsx
  src/components/ReservationFooter/ReservationFooter.tsx
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioInfoDock.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Swiper/DimSwiper.tsx
  src/hooks/useBookmark.ts
  src/hooks/useGetReservationData.ts
  src/hooks/useGetReservationList.ts
  src/hooks/useGetStudios.ts
  src/hooks/useLoginMutation.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
  src/pages/Home/components/LocationModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationCanceled.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Reservation/components/CancelModal.tsx
  src/pages/Reservation/components/CompleteMessage.tsx
  src/pages/Reservation/components/LocationModal.tsx
  src/pages/Reservation/components/Payment.tsx
  src/pages/Reservation/components/ScheduleInner.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
  src/pages/User/AuthVerification.tsx
  src/pages/User/ChangePassword.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
  src/pages/search/SearchResult.tsx
  src/store/useUserStore.ts
  src/types/types.ts
  src/utils/encryptUserData.ts
Labels: Deploy

#647 [S5] 찜한 사진관 UI 작업 중
  src/components/BackButton/BackButton.tsx
  src/components/Navigator/BookmarkNavigator.tsx
  src/hooks/useGetBookmarkList.ts
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/components/BookmarkStudioItem.tsx
Labels: Feat, UI

#648 [WEB3] 이용완료 및 예약취소 PC 화면 구현
  src/components/ReservationCard/RatingReview.tsx
  src/pages/Reservation/ReservationDetail.tsx
Labels: Feat, UI

#653 [S5] 찜한 사진관 페이지 작업 완료
  src/components/Bookmark/Bookmark.tsx
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioItem.tsx
  src/hooks/useGetBookmarkList.ts
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/components/BookmarkStudioItem.tsx
  src/pages/User/components/BookmarkedStudioItem.tsx
  src/pages/User/components/BookmarkedStudioList.tsx
Labels: Feat, UI

#649 [S5] 내 리뷰 페이지 UI 및 반응형 구현
  src/components/Navigator/ReservationNavigator.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/User/MyReviews.tsx
  src/utils/sortReservations.tsx
Labels: Feat, UI, Refactor

#651 [WEB1] 메인 PC 좌측 필터링 영역 스타일 개선
  src/components/Button/Button.tsx
  src/components/CopyButton/CopyLocation.tsx
  src/components/Filter/FilterSort.tsx
  src/components/FilterPriceSlide/FilterPriceSlidePC.tsx
  src/components/Header/PCHeader.tsx
  src/components/Input/Input.tsx
  src/components/Navigator/BookmarkNavigator.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/ReservationCard/RatingReview.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/components/ReservationFooter/ReservationFooter.tsx
  src/components/Search/RecentSearches.tsx
  src/components/Search/SearchBar.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/components/Studio/StudioInfoDock.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Swiper/DimSwiper.tsx
  src/components/Toast/Toast.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/LocationSelector.tsx
  src/pages/Home/components/PCFilterWrapper.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/Reservation/components/CompleteMessage.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/Profile.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Variables.tsx
Labels: UI

#655 Version 0.7.1: 작업 내용 배포
  src/components/BackButton/BackButton.tsx
  src/components/Bookmark/Bookmark.tsx
  src/components/Button/Button.tsx
  src/components/CopyButton/CopyLocation.tsx
  src/components/Filter/FilterSort.tsx
  src/components/FilterPriceSlide/FilterPriceSlidePC.tsx
  src/components/Header/PCHeader.tsx
  src/components/Input/Input.tsx
  src/components/Navigator/BookmarkNavigator.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/ReservationCard/RatingReview.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/components/ReservationFooter/ReservationFooter.tsx
  src/components/Search/RecentSearches.tsx
  src/components/Search/SearchBar.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioInfoDock.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Swiper/DimSwiper.tsx
  src/components/Toast/Toast.tsx
  src/hooks/useGetBookmarkList.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/LocationSelector.tsx
  src/pages/Home/components/PCFilterWrapper.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/Reservation/components/CompleteMessage.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/MyReviews.tsx
  src/pages/User/Profile.tsx
  src/pages/User/components/BookmarkedStudioItem.tsx
  src/pages/User/components/BookmarkedStudioList.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Variables.tsx
  src/utils/sortReservations.tsx
  tests/Bookmark.test.tsx
Labels: Deploy

#660 [S5] 찜한 사진관 패딩 수정
  src/pages/User/BookmarkedStudios.tsx
Labels: UI

#661 [Hotfix] 403 에러로 로그인 페이지 이동 시 발생하는 토스트 렌더링 경고 해결
  src/pages/Reservation/ReservationList.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/MyReviews.tsx
Labels: Bug

#663 [QA] 홈 화면에서 PC → 모바일로 변경 시 `isFixed`의 상태 변경
  src/pages/Home/Home.tsx
Labels: Bug

#666 [QA] 너무 작은 `rem` 단위를 `px`로 변경
  src/components/Bookmark/Bookmark.tsx
  src/components/Navigator/BookmarkNavigator.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/NoPic/NoPic.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Toast/Toast.tsx
  src/pages/User/components/BookmarkedStudioItem.tsx
Labels: Refactor

#667 [QA] React-Helmet 추가
  src/pages/Reservation/ReservationCanceled.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/MyPage.tsx
Labels: Refactor, QA

#665 [Hotfix] 복호화된 유저 이메일을 사용한 비밀번호 변경 요청 처리
  src/pages/User/MyPage.tsx
  src/pages/User/PasswordConfirm.tsx
Labels: Hotfix

#668 [Fix] 중복된 import 삭제
  src/pages/User/MyPage.tsx
Labels: Hotfix

#669 [WEB1] PC버전 필터 영역 변경으로 인한 컨텐츠 정렬
  src/components/BookingSearchContainer/BookingButton.tsx
  src/components/Header/PCHeader.tsx
  src/components/Studio/StudioItem.tsx
  src/pages/Home/Home.tsx
Labels: UI

#673 [QA] 스튜디오 조회 결과 없음 페이지 여백 수정
  src/components/NoResult/NoResult.tsx
Labels: UI, QA

#671 [QA] 포트원 카카오페이 결제 pg사 명시
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/Payment.tsx
Labels: Bug

#674 [QA] 매장정보 로그 삭제
  src/components/Header/PCHeader.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
Labels: QA

#677 [웹접근성] 탭 포커스 개선 - focus-visible 상태 스타일 개선, 모달/달력/시간 선택 컴포넌트 개선
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/hooks/useTabFocus.ts
  src/pages/Home/components/SelectTime.tsx
  src/styles/GlobalStyles.tsx
Labels: Refactor

#676 [QA] 약관 동의 모달에 하단 여백 추가
  src/pages/Reservation/components/PolicyModal.tsx
Labels: UI, QA

#678 Version 0.8.0: QA 내용 배포
  src/components/BookingSearchContainer/BookingButton.tsx
  src/components/Bookmark/Bookmark.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Header/PCHeader.tsx
  src/components/Modal/Modal.tsx
  src/components/Navigator/BookmarkNavigator.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/NoPic/NoPic.tsx
  src/components/NoResult/NoResult.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Toast/Toast.tsx
  src/hooks/useTabFocus.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationCanceled.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/Reservation/components/Payment.tsx
  src/pages/Reservation/components/PolicyModal.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/MyReviews.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/components/BookmarkedStudioItem.tsx
  src/styles/GlobalStyles.tsx
Labels: Deploy

#680 [QA] 스튜디오 메뉴 상세 - 시계 아이콘 색상 변경
  public/img/icon-clock-gray800.svg
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
Labels: UI, QA

#684 [QA] 스튜디오 상세 페이지 진입 시 발생하는 무한로딩 문제 해결
  src/components/Studio/StudioInfoDock.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: UI, Hotfix, QA

#685 Version 0.8.1: 스튜디오 상세 오류 해결 후 배포
  public/img/icon-clock-gray800.svg
  src/components/Studio/StudioInfoDock.tsx
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
Labels: Deploy

#688 [QA] 예약하기 푸터 z-index 수정
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Studio/StudioDetailLayout.tsx
Labels: UI, Hotfix, QA

#689 Hotfix: 스튜디오 상세 오류 수정 후 배포
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Studio/StudioDetailLayout.tsx
Labels: Deploy, Hotfix

#692 [QA] 모달 QA 반영
  src/components/Modal/Modal.tsx
  src/components/Share/ShareModal.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
Labels: QA

#690 [웹접근성] 모달 내 버튼 keydown 이벤트 발생시 포커스 오류 개선중
  src/components/BookingSearchContainer/BookingButton.tsx
  src/hooks/useTabFocus.ts
  src/pages/Home/components/LocalDateSelectionModal.tsx
Labels: Bug, Refactor

#686 [QA] StudioItem 폰트 및 아이콘 크기 수정
  src/components/Studio/StudioItem.tsx
Labels: UI, QA

#682 [QA] PC버전 전체 레이아웃 하단 여백 추가 및 그에 따른 기존 여백 삭제
  src/pages/Home/Home.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/styles/GlobalStyles.tsx
Labels: UI, QA

#694 [QA] 예약하기 푸터 padding 수정
  src/components/ReservationFooter/ReservationFooter.tsx
  src/pages/Reservation/ReservationSchedule.tsx
Labels: UI, QA

#695 [S2] 스튜디오 상세 조회 시 북마크 여부 반영
  src/components/Studio/StudioInfo.tsx
  src/hooks/useGetStudioDetail.ts
  src/hooks/useGetStudios.ts
  src/types/types.ts
Labels: Refactor
