Repository TEAM-FLASH/Toucheese-FE, pull requests merged in 2025-05, with the labels that each got.

#696 [QA] StudioItem 탭 포커스 개선
  src/components/Studio/StudioItem.tsx
  src/pages/Home/Home.tsx
Labels: Refactor, QA

#697 [웹접근성] tabtrap 및 첫번째 요소 포커싱 구현
  index.html
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Button/Button.tsx
  src/components/Modal/Modal.tsx
  src/components/Share/ShareButton.tsx
  src/components/Share/ShareModal.tsx
  src/components/Studio/StudioInfo.tsx
  src/components/Swiper/DimSwiper.tsx
  src/hooks/useTabFocus.ts
  src/hooks/useTabFocusObserver.ts
  src/pages/Home/components/LocationSelector.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/CancelModal.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
Labels: Feat, Refactor

#701 [QA] 스튜디오 메뉴 QA 반영
  src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
Labels: UI, QA

#706 [WEB1] PC버전 NoPic 컴포넌트 작업 완료
  public/img/icon-nopic-1.svg
  public/img/icon-nopic-2.svg
  public/img/icon-nopic-5.svg
  public/img/icon-nopic-6.svg
  public/img/icon-nopic-pc.svg
  src/components/NoPic/NoPic.tsx
  src/components/Studio/StudioItem.tsx
Labels: UI

#705 [QA] PC 헤더의 z-index 수정
  src/components/Header/PCHeader.tsx
Labels: UI, QA

#709 [QA] 필터링 정렬의 UI를 개선한다
  src/components/Button/Button.tsx
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterSort.tsx
Labels: UI, QA

#712 [QA] 스튜디오 메인페이지의 UI를 수정한다.
  src/pages/Studio/StudioDetailLayout.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: UI, QA

#711 [QA] 스튜디오 아이템 margin 문제 해결
  src/components/Bookmark/Bookmark.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Studio/StudioList.tsx
  src/pages/Home/Home.tsx
Labels: Bug, UI, QA

#714 [QA] 유저 정보 관리 페이지의 PC버전 UI를 구현하고 기존 적용된 UI 버그를 해결한다.
  src/pages/User/ChangePassword.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
Labels: Bug, UI, QA

#707 [QA] 예약전 로그인 후 원래 페이지 돌아가는 로직 추가
  src/pages/Home/Home.tsx
Labels: QA

#698 [QA] 예약 카드 스타일 추가
  src/components/ReservationCard/RatingReview.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/pages/User/MyPage.tsx
  src/types/types.ts
Labels: Feat, UI

#715 [QA] 스튜디오 예약 상세 Ul 개선
  src/components/CopyButton/CopyLocation.tsx
  src/components/Kakao/KakaoMap.tsx
  src/components/Studio/StudioList.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/ReservationInfo.tsx
  src/pages/search/SearchResult.tsx
Labels: UI, QA

#720 [QA] 내 리뷰, 예약 취소 QA
  src/pages/Reservation/ReservationList.tsx
  src/pages/User/MyReviews.tsx
  src/styles/GlobalStyles.tsx
Labels: UI, QA

#721 [QA] 찜한 사진관 데이터가 없을 시 예외 처리
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/MyPage.tsx
Labels: Refactor, QA

#727 [QA] NoPic 컴포넌트를 이미지로 변경
  public/img/icon-nopic-1.svg
  public/img/icon-nopic-2.svg
  public/img/icon-nopic-5.svg
  public/img/icon-nopic-6.svg
  public/img/img-nopic1.svg
  public/img/img-nopic2.svg
  public/img/img-nopic3.svg
  public/img/img-nopic4.svg
  public/img/img-nopic5.svg
  public/img/img-nopic6.svg
  public/img/img-nopic7.svg
  src/components/NoPic/NoPic.tsx
Labels: UI, QA

#730 [QA] 딤 스와이퍼 오류 개선
  src/components/Swiper/DimSwiper.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: Bug, QA

#731 [S4] 구글 로그인 작업 중
  src/pages/User/Auth.tsx
  src/pages/User/GoogleCallback.tsx
  src/routes.tsx
Labels: Feat

#732 [QA] NoPic 이미지 변경
  public/img/img-nopic1.svg
  public/img/img-nopic2.svg
  public/img/img-nopic3.svg
  public/img/img-nopic4.svg
  public/img/img-nopic5.svg
  public/img/img-nopic6.svg
  public/img/img-nopic7.svg
Labels: UI, QA

#736 [QA] 모바일버전 예약 내역 좌우 패딩 추가
  src/pages/Reservation/ReservationList.tsx
Labels: UI, QA

#737 [QA] StudioInfoDock 우측 여백 추가
  src/components/Studio/StudioInfoDock.tsx
Labels: UI, QA

#738 [QA] 모바일 스튜디오 메뉴 상세 상단 여백 제거
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
Labels: UI, QA

#740 [QA] 접근성 고려 마크업 변경
  src/components/Bookmark/Bookmark.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/components/Studio/StudioItem.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/components/BookmarkedStudioItem.tsx
Labels: UI, Refactor, QA

#743 [QA] 튜디오 메뉴 페이지 QA 반영
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
Labels: UI, QA

#741 Version 0.8.3: QA 작업물 배포
  .github/workflows/deploy.yml
  public/img/icon-nopic-1.svg
  public/img/icon-nopic-2.svg
  public/img/icon-nopic-5.svg
  public/img/icon-nopic-6.svg
  public/img/img-nopic1.svg
  public/img/img-nopic2.svg
  public/img/img-nopic3.svg
  public/img/img-nopic4.svg
  public/img/img-nopic5.svg
  public/img/img-nopic6.svg
  public/img/img-nopic7.svg
  src/components/Bookmark/Bookmark.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/NoPic/NoPic.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/components/Studio/StudioInfoDock.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Swiper/DimSwiper.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/pages/User/Auth.tsx
  src/pages/User/BookmarkedStudios.tsx
  src/pages/User/GoogleCallback.tsx
  src/pages/User/components/BookmarkedStudioItem.tsx
  src/routes.tsx
Labels: Deploy, QA

#747 [QA] 예약 카드 마크업 변경
  src/components/ReservationCard/ReservationCard.tsx
Labels: Refactor, QA

#748 [S4] 내 리뷰 - 리뷰 작성 전, 후 구분
  src/pages/User/MyReviews.tsx
Labels: Feat

#750 Hotfix: Deploy 설정 변경
  .github/workflows/deploy.yml
  src/components/ReservationCard/ReservationCard.tsx
  src/components/Studio/StudioInfo.tsx
  src/components/Studio/StudioItem.tsx
  src/pages/User/MyReviews.tsx
Labels: Deploy, Hotfix

#749 [S4] 소셜 로그인 로직 추가
  src/pages/User/AuthVerification.tsx
  src/pages/User/GoogleCallback.tsx
  src/pages/User/KakaoCallback.tsx
  src/pages/User/signupSuccess.tsx
  src/types/types.ts
Labels: Refactor, QA

#752 [QA] 비밀번호 변경시 Query String 노출 이슈 해결 및 모바일 본인인증 및 유저 정보 변경 플로우 개선
  src/hooks/useRemoveQueryParams.ts
  src/pages/User/AuthVerification.tsx
  src/pages/User/ChangePassword.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
  src/pages/User/components/AuthRedirectHandler.tsx
  src/pages/User/components/PasswordChangeSuccessModal.tsx
  src/pages/User/components/RemoveQueryParams.tsx
  src/pages/User/components/userDataChangeSuccessModal.tsx
  src/routes.tsx
  src/store/useTempStore.ts
  src/utils/encryptUserData.ts
Labels: Bug, UI, QA

#751 [QA] 로그인 페이지 이미지 수정 & 리뷰 페이지 비율 수정
  package.json
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/User/Auth.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/routes.tsx
Labels: QA

#753 Version 0.9.0: QA 결과물 배포
  index.html
  public/img/img-auth.svg
  src/hooks/useRemoveQueryParams.ts
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/User/Auth.tsx
  src/pages/User/AuthVerification.tsx
  src/pages/User/ChangePassword.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/GoogleCallback.tsx
  src/pages/User/KakaoCallback.tsx
  src/pages/User/LoginWithEmailPage.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
  src/pages/User/components/AuthRedirectHandler.tsx
  src/pages/User/components/PasswordChangeSuccessModal.tsx
  src/pages/User/components/RemoveQueryParams.tsx
  src/pages/User/components/userDataChangeSuccessModal.tsx
  src/pages/User/signupSuccess.tsx
  src/routes.tsx
  src/store/useTempStore.ts
  src/types/types.ts
  src/utils/encryptUserData.ts
Labels: Deploy, QA

#755 [QA] 찜한 사진관 평점 수정
  src/pages/User/components/BookmarkedStudioItem.tsx
Labels: UI, QA

#754 [Docs] README.md 이미지 작업 중
  README.md
Labels: Docs

#756 [QA] 북마크 403 에러 핸들링
  src/components/Bookmark/Bookmark.tsx
  src/hooks/useBookmark.ts
Labels: Refactor, QA

#761 [QA] 이메일 로그인 사이즈, 아이템 화살표 제거 아이콘 사이즈 수정
  package.json
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/User/Auth.tsx
Labels: QA

#762 [QA] 예약상세 예약자정보 복호화 추가
  src/pages/Reservation/ReservationCheck.tsx
Labels: Feat, QA

#764 [QA] 결제요청 accessToken 헤더 추가
  src/pages/Reservation/components/Payment.tsx
Labels: Feat, QA

#767 [QA] 예약 관련 스타일 및 로직 수정
  src/pages/Reservation/ReservationList.tsx
  src/pages/User/MyPage.tsx
Labels: UI, Refactor, QA

#765 [QA] 소셜 로그인/회원가입 로직 수정
  src/pages/User/AuthVerification.tsx
  src/pages/User/GoogleCallback.tsx
  src/pages/User/KakaoCallback.tsx
  src/pages/User/components/SocialCallback.tsx
Labels: Refactor, Hotfix, QA

#768 [Docs] README.md 페이지 이미지 작업 중
  README.md
Labels: Docs
