Repository TEAM-FLASH/Toucheese-FE, pull requests merged in 2025-02, with the labels that each got.

#355 [S5] 로딩 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/json/loading.json
  src/components/Loading/Loading.tsx
Labels: Feat, UI

#357 Version 0.3.1: Story 4 및 Story 5 작업물 배포
  package.json
  pnpm-lock.yaml
  public/img/icon-arrow-right-black.svg
  public/img/icon-calendar-yellow.svg
  public/img/icon-check-white-radius.svg
  public/img/icon-myreview.svg
  public/img/icon-rating-disabled.svg
  public/img/icon-rating.svg
  public/img/icon-studio-black.svg
  public/img/icon-studio-yellow.svg
  public/img/icon-valid.svg
  src/App.tsx
  src/assets/json/loading.json
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/createCalendar.tsx
  src/components/Input/Input.tsx
  src/components/Loading/Loading.tsx
  src/components/Modal/Modal.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/ReservationCard/RatingReview.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/components/ReservationCard/StatusChip.tsx
  src/components/TextArea/TextArea.tsx
  src/hooks/useGetAvailableDate.tsx
  src/hooks/useGetReservationList.ts
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Reservation/components/CancelModal.tsx
  src/pages/Reservation/components/Payment.tsx
  src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
  src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
  src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
  src/pages/User/AuthVerification.tsx
  src/pages/User/ChangeProfile.tsx
  src/pages/User/MyPage.tsx
  src/pages/User/PasswordConfirm.tsx
  src/pages/User/Profile.tsx
  src/pages/User/SignUp.tsx
  src/pages/User/signupSuccess.tsx
  src/routes.tsx
  src/store/useReservationStore.ts
  src/store/useSignupStore.ts
  src/styles/Common.tsx
  src/styles/GlobalStyles.tsx
  src/types/types.ts
Labels: Deploy

#359 [QA1] 체크박스 공통 UI로 수정
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
Labels: Hotfix, QA

#362 [QA1] 스튜디오 최저가의 천단위마다 쉼표 추가
  src/components/Studio/StudioItem.tsx
Labels: UI

#366 [QA1] 마이페이지 UI 수정
  public/img/icon-calendar-yellow.svg
  public/img/icon-myreview.svg
  public/img/icon-studio-gray.svg
  src/components/ReservationCard/ReservationCard.tsx
  src/pages/User/MyPage.tsx
Labels: UI, Hotfix

#368 [QA1] 메인화면 전체지역 섹션 부분의 여백 조정
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/Studio/StudioList.tsx
  src/pages/Home/Home.tsx
Labels: UI

#364 [QA1] 홈 화면에 로딩, React-Helmet 적용
  src/components/Studio/StudioList.tsx
  src/pages/Home/Home.tsx
Labels: UI, Refactor

#370 [QA1] nopic 이미지 교체
  public/img/img-nopic.png
Labels: Chore

#372 [QA1] 예약 내역 헤더 높이 조정
  src/pages/Reservation/ReservationList.tsx
Labels: UI

#374 [QA1] 예약화면 여백 조정 및 요청사항 글자수 적용
  src/pages/Reservation/ReservationCheck.tsx
Labels: UI

#376 [QA1] 복사 완료 UI를 토스트 메시지로 변경
  public/img/icon-content_copy.svg
  src/components/CopyButton/CopyLocation.tsx
  src/components/Kakao/KakaoMap.tsx
  src/components/Share/ShareButton.tsx
  src/components/Share/ShareOptions.tsx
Labels: UI

#379 [QA1] 검색화면 스타일 변경
  public/img/icon-delete.svg
  public/img/icon-xcircle.svg
  src/pages/search/components/RecentSearches.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/components/TrendingStudios.tsx
Labels: UI

#380 [QA1] 예약 내역 헤더의 box-shadow 삭제
  src/pages/Reservation/ReservationList.tsx
Labels: UI

#386 [QA1] 네이버페이 결제취소 및 실패 시 리다이렉트 로직 수정
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationNpayCallback.tsx
  src/pages/Reservation/components/Payment.tsx
  src/routes.tsx
Labels: Feat, QA

#384 Version 0.4.0: QA 작업물 테스트 배포
  .github/workflows/deploy.yml
  public/img/icon-calendar-yellow.svg
  public/img/icon-content_copy.svg
  public/img/icon-delete.svg
  public/img/icon-myreview.svg
  public/img/icon-studio-gray.svg
  public/img/icon-xcircle.svg
  public/img/img-nopic.png
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/CopyButton/CopyLocation.tsx
  src/components/Kakao/KakaoMap.tsx
  src/components/Navigator/ReservationNavigator.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/ReservationCard/ReservationCard.tsx
  src/components/Share/ShareButton.tsx
  src/components/Share/ShareOptions.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Studio/StudioList.tsx
  src/pages/Home/Home.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationList.tsx
  src/pages/Reservation/ReservationNpayCallback.tsx
  src/pages/Reservation/components/Payment.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/User/MyPage.tsx
  src/pages/search/components/RecentSearches.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/components/TrendingStudios.tsx
  src/routes.tsx
Labels: Deploy

#383 [QA1] 날짜/시간 선택 모달 사용성 및 오류 개선
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/SelectTime.tsx
  src/store/useSelectDateStore.ts
  src/store/useSelectTimeStore.ts
Labels: Bug, UI, QA

#390 [QA1] 회원가입 플로우의 비밀번호 검증 오류를 해결한다.
  src/pages/User/SignUp.tsx
  tests/SignUp.test.tsx
Labels: Test, QA

#393 [QA1] 메인페이지 필터링 리셋 버튼의 QA를 적용한다
  src/pages/Home/Home.tsx
Labels: UI, Refactor

#392 [QA1] QA 윤우중 담당 부분 오류 수정 및 작업완료
  src/components/FilterPriceSlide/FilterPriceSlide.tsx
  src/components/Input/Input.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/hooks/useResetState.ts
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/StarRating.tsx
  src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/User/Auth.tsx
Labels: Bug, Feat, Hotfix, QA

#389 [QA1] 공통 컴포넌트에 QA 반영
  src/components/Modal/Modal.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/styles/Common.tsx
  src/styles/GlobalStyles.tsx
Labels: UI, QA

#396 [QA1] 지역선택 QA를 적용한다
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
Labels: UI, Hotfix, QA

#394 Version 0.4.1: QA 작업물 배포
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Calendar/Calendar.tsx
  src/components/FilterPriceSlide/FilterPriceSlide.tsx
  src/components/Input/Input.tsx
  src/components/Modal/Modal.tsx
  src/components/ServiceAvailability/ServiceAvailability.tsx
  src/hooks/useResetState.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/DateBottomSheet.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
  src/pages/Home/components/LocationBottomSheet.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/DropDown.tsx
  src/pages/Studio/StudioReview/components/StarRating.tsx
  src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
  src/pages/User/Auth.tsx
  src/pages/User/SignUp.tsx
  src/store/useSelectDateStore.ts
  src/store/useSelectTimeStore.ts
  src/styles/Common.tsx
  src/styles/GlobalStyles.tsx
  tests/SignUp.test.tsx
Labels: Deploy

#399 [QA2] 페이지 이동시 스크롤 최상단 이동
  src/App.tsx
  src/hooks/useScrollToTop.ts
Labels: Feat

#400 [QA2] "결과 없음" 컴포넌트 제작
  public/img/icon-noresult.svg
  src/components/NoResult/NoResult.tsx
  src/components/Studio/StudioList.tsx
Labels: Feat, UI

#403 [QA2] 사진이 없는 스튜디오를 배너 형태로 변경
  public/img/icon-nopic.svg
  src/components/NoPic/NoPic.tsx
  src/components/Studio/StudioItem.tsx
  src/components/Swiper/ImageSwiper.tsx
Labels: Feat, UI

#405 [QA2] 마이페이지 회원정보 QA를 적용한다.
  src/pages/Home/components/LocationBottomSheet.tsx
  src/pages/User/Profile.tsx
Labels: Bug, QA

#407 [QA2] 버튼 공통 컴포넌트의 QA를 적용한다
  src/components/Button/Button.tsx
Labels: QA

#409 [QA2] 스튜디오 상세페이지의 포트폴리오 이미지 오류 QA를 적용한다.
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/pages/User/Profile.tsx
Labels: Hotfix, QA

#412 [QA2] 스튜디오 상세페이지 QA를 적용한다
  src/components/Header/Header.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: UI, Refactor

#413 [Hotfix] 스튜디오 메인 페이지의 scrollY 값을 수정한다.
  src/pages/Studio/StudioMain/StudioMain.tsx
Labels: Hotfix

#414 [QA2] 내비게이터 배지 디자인 변경
  public/img/icon-nav-badge.svg
  src/components/Navigator/ReservationNavigator.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/components/Navigator/ThemeNavigator.tsx
Labels: UI

#418 [QA2] 마이페이지 QA리스트를 반영한다.
  public/img/icon-arrow-right-black.svg
  src/components/ReservationCard/ReservationCard.tsx
  src/components/ReservationCard/StatusChip.tsx
  src/pages/User/MyPage.tsx
Labels: Feat, UI, Hotfix, QA

#422 [QA2] 슬라이드시 왼쪽 여백 제거
  src/components/Swiper/ImageSwiper.tsx
Labels: UI, QA

#421 [QA2] 페이지 이동 시 스크롤 최상단으로 이동하지 않는 버그 해결
  src/App.tsx
  src/components/layout/Layout.tsx
  src/routes.tsx
Labels: Bug

#424 QA2] 지역 및 일시 선택 모달 사용성 개선
  src/pages/Home/components/LocalDateSelectionModal.tsx
Labels: QA

#427 [QA2] 메뉴 상세페이지 QA리스트를 적용한다.
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
Labels: Feat, UI, Hotfix, QA

#428 [QA2] 포트폴리오 딤모달에서 스와이프를 하면 깜빡이는 현상 개선
  src/components/Swiper/DimSwiper.tsx
Labels: Bug, QA

#430 [QA2] 예약상세 전화기능 및 위치 추가
  src/pages/Reservation/ReservationDetail.tsx
  src/pages/Reservation/components/LocationModal.tsx
Labels: Feat, QA

#436 [QA2] 스튜디오 메인 페이지의 header, navigator sticky 기능을 구현한다
  src/components/Button/Button.tsx
  src/components/Header/Header.tsx
  src/components/Navigator/StudioNavigator.tsx
  src/pages/Studio/StudioMain/StudioMain.tsx
  src/types/types.ts
Labels: Hotfix, QA

#440 [QA2] 마이페이지 가로 스크롤 제거
  src/pages/User/MyPage.tsx
Labels: Hotfix, QA

#432 [QA2] 네이버페이 결제 리다이렉트 시 로딩 중복 제거
  src/App.tsx
  src/pages/Reservation/ReservationNpayCallback.tsx
Labels: Feat, Hotfix, QA

#444 [QA2] 바텀시트 컨텐츠와 함께 드래그되는 이슈 해결
  src/components/BottomSheet/BottomSheet.tsx
Labels: Bug, Hotfix, QA

#439 [Q2] 이미지 슬라이드 양쪽 여백 추가
  src/components/Swiper/ImageSwiper.tsx
  src/pages/Home/Home.tsx
  src/styles/GlobalStyles.tsx
Labels: UI, QA

#446 [QA2] body 위쪽 padding 제거 및 스튜디오 메뉴 페이지 UI 수정
  src/components/ReservationCard/ReservationCard.tsx
  src/pages/Studio/StudioMenu/StudioMenu.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
  src/pages/Studio/StudioMenu/StudioMenuItem.tsx
  src/pages/User/MyPage.tsx
  src/styles/GlobalStyles.tsx
Labels: UI, Hotfix, QA

#442 [QA2] ImageSwiper pagination 스타일 오류 이슈 해결
  src/components/Swiper/ImageSwiper.tsx
Labels: Hotfix, QA

#450 [WEB1] 상단 padding 제거로 인한 홈화면, 예약 내역 화면 UI 수정
  src/pages/Home/Home.tsx
  src/pages/Reservation/ReservationList.tsx
Labels: UI

#435 [QA2] 필터 px 수정 및 스튜디오 리뷰 아이템 메뉴 내용 프롭 추가
  src/components/FilterPriceSlide/FilterPriceSlide.tsx
  src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
  src/pages/Studio/StudioReview/StudioReview.tsx
  src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
Labels: Feat, QA

#453 [QA2] fullsize 모달 엑스버튼 추가 및 사용하지 않는 변수 삭제
  public/img/icon-close-gray800.svg
  src/components/Modal/Modal.tsx
  src/components/Swiper/ImageSwiper.tsx
  src/pages/Home/components/LocalDateSelectionModal.tsx
Labels: UI, QA

#459 [WEB1] 에러 바운더리 설정
  package.json
  pnpm-lock.yaml
  public/img/icon-404.svg
  src/App.tsx
  src/components/Error/Error.tsx
  src/components/Error/ErrorBoundary.tsx
  src/hooks/useGetAvailableDate.tsx
  src/pages/Home/components/SelectTime.tsx
  src/pages/Reservation/ReservationSchedule.tsx
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/routes.tsx
  tests/StudioItem.test.tsx
  tests/StudioList.test.tsx
  tests/useGetStudios.test.tsx
Labels: Feat, Chore

#458 [QA2] 네이버페이 결제 처리 개선 및 스타일 수정
  src/App.tsx
  src/components/CopyButton/CopyLocation.tsx
  src/components/Header/Header.tsx
  src/pages/Reservation/ReservationCheck.tsx
  src/pages/Reservation/ReservationComplete.tsx
  src/pages/Reservation/ReservationNpayCallback.tsx
  src/pages/Reservation/components/Payment.tsx
  src/routes.tsx
Labels: Feat, QA

#460 [WEB1] PC 반응형 작업 중
  public/img/icon-arrowdown-white.svg
  public/img/logo-pc.svg
  src/components/BookingSearchContainer/BookingButton.tsx
  src/components/BookingSearchContainer/BookingSearchContainer.tsx
  src/components/Navigator/ThemeNavigator.tsx
  src/components/NoPic/NoPic.tsx
  src/components/PCHeader/PCHeader.tsx
  src/components/SearchButton/SearchButton.tsx
  src/components/Studio/StudioItem.tsx
  src/components/UserButton/UserButton.tsx
  src/hooks/useGetWindowWidth.ts
  src/pages/Home/Home.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Variables.tsx
  src/utils/remToPx.ts
Labels: UI

#465 [WEB1] 에러 바운더리 적용
  src/hooks/useBookmark.ts
  src/hooks/useGetReservationList.ts
  src/hooks/useGetStudios.ts
Labels: Chore, Refactor

#464 [WEB1] PC 반응형 설정
  src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
  src/styles/BreakPoint.tsx
  src/styles/Common.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Variables.tsx
Labels: UI
